// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["服务认证"],
                "summary": "用户登录",
                "description": "使用账号密码换取 ESB 用户登录 token。用户 token 存储在 Redis，默认 2 小时有效。agent 或系统对系统调用建议使用 X-API-Token APP TOKEN。",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/LoginResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "401": {
                        "description": "账号或密码错误",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "produces": ["application/json"],
                "tags": ["服务认证"],
                "summary": "退出登录",
                "description": "删除 Redis 中的用户登录 token。APP TOKEN 是配置文件中的静态令牌，不受退出登录影响。",
                "security": [
                    {
                        "UserBearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "退出成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "401": {
                        "description": "token 无效或已过期",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/api/esb/v1/{url}": {
            "get": {
                "produces": ["application/json"],
                "tags": ["OpenAPI 通用代理"],
                "summary": "GET 转发第三方完整 URL",
				"description": "把第三方完整 URL 放在 /api/esb/v1/ 后面，例如 /api/esb/v1/https://gaiaopenapi-s.copm.com.cn/atd-webapi/api/v1/workflow/apply/list。APP TOKEN 使用 X-API-Token，且不要加 Bearer。Swagger 对完整 URL 路径参数支持有限，实际联调建议使用 Apifox、Postman 或 curl。",
                "security": [
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "第三方完整 URL，包含 https://、域名、路径和查询参数。Swagger 展示为 {url}，实际路由会接收后面的完整路径。",
                        "name": "url",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "转发成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "401": {
                        "description": "APP TOKEN 缺失、错误或无应用权限",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "第三方接口返回异常或 ESB 转发失败",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "post": {
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["OpenAPI 通用代理"],
                "summary": "POST 转发第三方完整 URL",
                "description": "把请求方法、query 和 JSON body 原样转发给第三方。ESB 会自动处理第三方 OAuth token、固定请求头和响应包装。",
                "security": [
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "第三方完整 URL，包含 https://、域名、路径和查询参数。",
                        "name": "url",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "需要转发给第三方的 JSON 请求体",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/ProxyBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "转发成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "401": {
                        "description": "APP TOKEN 缺失、错误或无应用权限",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "第三方接口返回异常或 ESB 转发失败",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "put": {
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["OpenAPI 通用代理"],
                "summary": "PUT 转发第三方完整 URL",
                "description": "使用 X-API-Token 调用。APP TOKEN 是普通应用令牌，不要加 Bearer。",
                "security": [
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "第三方完整 URL，包含 https://、域名、路径和查询参数。",
                        "name": "url",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "需要转发给第三方的 JSON 请求体",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/ProxyBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "转发成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "401": {
                        "description": "APP TOKEN 缺失、错误或无应用权限",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "第三方接口返回异常或 ESB 转发失败",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            },
            "delete": {
                "produces": ["application/json"],
                "tags": ["OpenAPI 通用代理"],
                "summary": "DELETE 转发第三方完整 URL",
                "description": "使用 X-API-Token 调用。APP TOKEN 是普通应用令牌，不要加 Bearer。",
                "security": [
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "第三方完整 URL，包含 https://、域名、路径和查询参数。",
                        "name": "url",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "转发成功",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "401": {
                        "description": "APP TOKEN 缺失、错误或无应用权限",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "500": {
                        "description": "第三方接口返回异常或 ESB 转发失败",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiTokenAuth": {
            "type": "apiKey",
            "name": "X-API-Token",
            "in": "header",
            "description": "ESB APP TOKEN，直接填写 token 原值，不要加 Bearer。"
        },
        "UserBearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "用户登录 token，格式：Bearer <user-token>。"
        }
    },
    "definitions": {
        "LoginRequest": {
            "type": "object",
            "required": ["username", "password"],
            "properties": {
                "username": {
                    "type": "string",
                    "example": "admin"
                },
                "password": {
                    "type": "string",
                    "example": "admin123"
                }
            }
        },
        "LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "msg": {
                    "type": "string",
                    "example": "ok"
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "token": {
                            "type": "string"
                        },
                        "token_type": {
                            "type": "string",
                            "example": "Bearer"
                        },
                        "expires_in": {
                            "type": "integer",
                            "example": 7200
                        },
                        "username": {
                            "type": "string",
                            "example": "admin"
                        }
                    }
                }
            }
        },
        "ProxyBody": {
            "type": "object",
            "additionalProperties": true
        },
        "Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "msg": {
                    "type": "string",
                    "example": "ok"
                },
                "data": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "ESB OpenAPI 通用代理服务",
	Description:      "ESB 对外提供用户登录、退出登录和 /api/esb/v1/{第三方完整URL} 通用代理接口。APP TOKEN 使用 X-API-Token，直接填写 token 原值，不要加 Bearer。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
